# Copyright 2021 Jetperch LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# GitHub actions
# See documentation: https://docs.github.com/en/actions

name: Windows
on: [push, pull_request, release]

concurrency:
  group: dut
  cancel-in-progress: false

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Configure python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Windows dependencies
        shell: cmd
        run: |
          echo Path = %Path%
          python3 -VV

      - name: Install python dependencies
        run: pip3 install -U -r requirements.txt

      - name: Run python unit tests
        run: python3 -m unittest

      - name: Build python source package
        run: python3 setup.py sdist

      - name: Upload python packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: dist/*
